[options]
db_user = odoo
db_password = odoo
db_name = motyx
addons_path = C:\Users\randy\OneDrive\Desktop\motostop\enterprise,
	C:\Users\randy\OneDrive\Desktop\motostop\custom_addons,
	C:\Users\randy\OneDrive\Desktop\motostop\odoo\addons,
	C:\Users\randy\OneDrive\Desktop\motostop\odoo-ads,
	C:\Users\randy\OneDrive\Desktop\motostop\addons_ia
admin_passwd = $pbkdf2-sha512$600000$S2lN6X2vFUKoFYKwNoZQyg$cUo3F0vmsonRB/ARQ.cdJXxK9a3tb8dVxl1D9mS56dxuiq9Xy4D3.lzTvEKgK2FNR632vxbJ1XF7U.IEa3DJzg
xmlrpc_interface = 0.0.0.0
log_level = debug


